### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by melchoir55** [scripty-bot/scripty-rewrite#16]
It would be helpful to see an implementation of docker in order to communicate the correct service level architecture (docker compose) and system level configuration (Dockerfile).

**Comment by randomairborne** [comment]
Hey! Scripty isn't really designed around using docker, and it's really designed to run on a bare-metal server. If you need more documentation on running the bot, that can be an arranged- joining our discord server would be a good first step, we'd be glad to implement some markdown documentation

**Comment by randomairborne** [comment]
Feel free to leave another comment if you have any further questions c:
